// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfvsafbhxnsefnsnzzwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmdnNhZmJoeG5zZWZuc256endwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNjU3MDYsImV4cCI6MjA2ODk0MTcwNn0.zIAa0PlLNIMgrnmyCpdazGiGv8RdT-mfas2mRGiIe5A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});